site_name: Rivirhouse Data Intelligence Blueprint
nav:
  - Home: README.md
  - Level 0: level_0.md
  - Level 1: level_1.md
  - Level 2: level_2.md
  - Models: modelling_framework.md
  - Standards: standards_and_conventions.md
  - About: about.md

theme: 
  name: mkdocs
  logo: img/rivir-logo.png
  prev_next_buttons_location: none

extra_css:
  - assets/custom.css
